<a href="https://colab.research.google.com/github/Cris986/senai-versoes-colaboracoes/blob/main/cris_dev.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
base_plano_saude = pd.read_csv('plano_saude_jones.csv')
base_plano_saude

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [3]:
x_plano_saude = base_plano_saude.iloc[:,0].values
x_plano_saude

array([18, 23, 28, 33, 38, 43, 48, 53, 58, 63])

In [4]:
y_plano_saude = base_plano_saude.iloc[:,1].values
y_plano_saude

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090])

In [6]:
x_plano_saude = x_plano_saude.reshape(-1,1)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
regressor_plano_saude = LinearRegression()

In [13]:
regressor_plano_saude.fit(x_plano_saude, y_plano_saude)

LinearRegression()

In [14]:
previsoes = regressor_plano_saude.predict(x_plano_saude)
previsoes

array([ 554.67272727,  864.01212121, 1173.35151515, 1482.69090909,
       1792.03030303, 2101.36969697, 2410.70909091, 2720.04848485,
       3029.38787879, 3338.72727273])

In [17]:
grafico = px.scatter(x = x_plano_saude.ravel(), y = y_plano_saude)
grafico.add_scatter(x = x_plano_saude.ravel(), y = previsoes, name = 'Regressão')
grafico.show()

In [ ]:
nome = 'Cris'
idade = '37'
município = 'Ibirama'
profissão = 'empresário'


In [ ]:
nome + ' ' + idade + ' ' + município + ' ' + profissão

'Cris 37 Ibirama empresário'

In [ ]:
print('Oi, meu nome é ' + nome + '.' + 'Tenho ' + idade + ' anos.' + 'Venho do município de ' + município + ' e sou ' + profissão + '.')

Oi, meu nome é Cris.Tenho 37 anos.Venho do município de Ibirama e sou empresário.


In [ ]:
a = 3*5
b = 1
c = 3+a
print (c)

18
